<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InnoAssemblyGroup>Core</InnoAssemblyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\native\Inno.Native.SDL3\Inno.Native.SDL3.csproj" PrivateAssets="compile" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\core\Inno.Core.Events\Inno.Core.Events.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Input\Inno.Core.Input.csproj" />
  </ItemGroup>
</Project>
