<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <InnoAssemblyScope>Editor</InnoAssemblyScope>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\Inno.Core.Reflection\Inno.Core.Reflection.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\core\Inno.Core.Scripting\Inno.Core.Scripting.csproj" PrivateAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\Inno.Core.Mathematics\Inno.Core.Mathematics.csproj" />
    <ProjectReference Include="..\Inno.Editor.Interactions\Inno.Editor.Interactions.csproj" />
    <ProjectReference Include="..\Inno.Editor.Core\Inno.Editor.Core.csproj" />
    <ProjectReference Include="..\..\platform\Inno.Platform.ImGui\Inno.Platform.ImGui.csproj" />
    <ProjectReference Include="..\..\render\Inno.Rendering\Inno.Rendering.csproj" />
  </ItemGroup>
</Project>
