using Inno.Audio;
using Inno.Scripting.Api;

[assembly: ScriptingApiNamespace(
    "InnoEngine.Audio",
    "Inno.Audio",
    ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(Audio), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioClipAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioClipMetadata), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioClipLoadMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioDeviceState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioPlaybackState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioCompletionReason), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioDistanceModel), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioCapabilities), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioStatistics), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioSpatialOptions), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioPlayOptions), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioVoiceParameters), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioListenerState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioClipHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioVoiceHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioBusHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioListenerHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioBusId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioProcessorId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioParameterId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioCodecId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioVoiceCompletedEvent), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IAudioDiagnosticSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioProcessorParameter), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioProcessorConfiguration), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioBusDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixer), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerBuilder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(SerializedAudioExtensionState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerFeatureConfiguration), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerFeatureExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerExtension), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(AudioMixerFeature), ScriptingApiScope.Runtime)]
