// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using BGCS.Runtime;

namespace Inno.Native.Sdl3
{
    [Flags]
    public enum SDLMessageBoxFlags : uint
	{
		Error = 0x00000010u,
		Warning = 0x00000020u,
		Information = 0x00000040u,
	}
}
