// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using BGCS.Runtime;

namespace Inno.Native.Sdl3
{
    [Flags]
	public enum SDLMouseButtonFlags : uint
	{
		None = 0,
		Left = 1u << 0,
		Middle = 1u << 1,
		Right = 1u << 2,
		X1 = 1u << 3,
		X2 = 1u << 4,
	}
}
