<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BGCS.Runtime" Version="1.0.1" PrivateAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Native.LibraryLoading\Inno.Native.LibraryLoading.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Native.ImGui\Inno.Native.ImGui.csproj" PrivateAssets="compile" />
  </ItemGroup>
</Project>