<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../graphics/Inno.Graphics/Inno.Graphics.csproj" />
    <ProjectReference Include="../../core/Inno.Core.Mathematics/Inno.Core.Mathematics.csproj" />
    <ProjectReference Include="../../../native/Inno.Native.Bgfx.Tools/Inno.Native.Bgfx.Tools.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
