using Inno.Core.Scripting;
using Inno.Rendering;

[assembly: ScriptingApiNamespace(
    "InnoEngine.Rendering",
    "Inno.Rendering",
    ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(RenderTexture), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTargetKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTarget), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderViewport), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrameData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequest), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderRequestSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderStage), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyType), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyBindingKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderProgramKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCullMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCompareFunction), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderRenderState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderContractId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniqueId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPassRoleId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderMetadataEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderKeywordDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderSourceAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPassDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniquePass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniqueDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureColorSpace), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GeometryAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRSourceKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderSourceLocation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRStageModule), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRPass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRModule), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderInterfaceBinding), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderInterface), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRValidationResult), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRValidator), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValueKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValue), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialMetadataEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyBlock), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPassResolution), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPassResolver), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPersistentResourceId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureSubresourceData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGeometrySection), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGeometry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderMaterialPass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderResourceService), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(SerializedRenderExtensionState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureConfiguration), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderDiagnosticSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderResourceRegistry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipeline), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineFeature), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrameStatistics), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsSettings), ScriptingApiScope.Runtime)]
