using Inno.Core.Scripting;
using Inno.Rendering;

[assembly: ScriptingApiNamespace(
    "InnoEngine.Rendering",
    "Inno.Rendering",
    ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(RenderPath), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(CameraProjection), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(CameraClearMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShadowCastingMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTexture), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTargetKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTarget), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderView), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequest), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderRequestSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(Camera), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(Light), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(DirectionalLight), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(PointLight), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(SpotLight), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MeshRenderer), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderStage), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyType), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCullMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCompareFunction), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderBlendMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderRenderState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderKeywordDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPassDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(BuiltinShaderPassTags), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(BuiltinShaderMetadataTags), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureColorSpace), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MeshAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRSourceKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderSourceLocation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRStageModule), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRPass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRModule), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderInterfaceBinding), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderInterface), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRValidationResult), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderIRValidator), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValueKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValue), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyBlock), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureConfiguration), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderQualitySettings), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderDiagnosticSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineOperationKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureBinding), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBufferBinding), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderUniformBinding), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(DirectionalShadowData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineOperation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderPipelineExecutor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(BuiltinRenderResources), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipeline), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineFeature), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrameStatistics), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsSettings), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBounds), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderLightKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderLightData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderObjectData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderCullingResults), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderWorldSnapshot), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPicking), ScriptingApiScope.Runtime)]
