<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Audio.Runtime\Inno.Audio.Runtime.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\extensibility\Inno.Extensibility.Types\Inno.Extensibility.Types.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\scripting\Inno.Scripting.Api\Inno.Scripting.Api.csproj" PrivateAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Audio\Inno.Audio.csproj" />
    <ProjectReference Include="..\..\scene\Inno.Scene\Inno.Scene.csproj" />
  </ItemGroup>
</Project>
