<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <InnoAssemblyGroup>Game</InnoAssemblyGroup>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\assets\Inno.Assets\Inno.Assets.csproj" />
    <ProjectReference Include="..\..\src\assets\Inno.Assets.Core\Inno.Assets.Core.csproj" />
    <ProjectReference Include="..\..\src\assets\Inno.Assets.Loader\Inno.Assets.Loader.csproj" />
    <ProjectReference Include="..\..\src\assets\Inno.Assets.Types\Inno.Assets.Types.csproj" />
    <ProjectReference Include="..\..\src\core\Inno.Core.Identity\Inno.Core.Identity.csproj" />
    <ProjectReference Include="..\..\src\core\Inno.Core.Reflection\Inno.Core.Reflection.csproj" />
    <ProjectReference Include="..\..\src\core\Inno.Core.Serialization\Inno.Core.Serialization.csproj" />
    <ProjectReference Include="..\..\src\engine\Inno.Engine.Assets\Inno.Engine.Assets.csproj" />
    <ProjectReference Include="..\..\src\engine\Inno.Engine.Scene\Inno.Engine.Scene.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.6.6" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
