<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <InnoAssemblyGroup>Core</InnoAssemblyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inno.Editor.Core\Inno.Editor.Core.csproj" />
    <ProjectReference Include="..\Inno.Editor.Assets\Inno.Editor.Assets.csproj" />
    <ProjectReference Include="..\Inno.Editor.Diagnostics\Inno.Editor.Diagnostics.csproj" />
    <ProjectReference Include="..\Inno.Editor.ImGui\Inno.Editor.ImGui.csproj" />
    <ProjectReference Include="..\Inno.Editor.Interactions\Inno.Editor.Interactions.csproj" />
    <ProjectReference Include="..\Inno.Editor.Scene\Inno.Editor.Scene.csproj" />
    <ProjectReference Include="..\Inno.Editor.Scripting\Inno.Editor.Scripting.csproj" />
    <ProjectReference Include="..\..\assets\Inno.Assets\Inno.Assets.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Framework\Inno.Core.Framework.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Events\Inno.Core.Events.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Logging\Inno.Core.Logging.csproj" />
    <ProjectReference Include="..\..\engine\Inno.Engine.Scene\Inno.Engine.Scene.csproj" />
    <ProjectReference Include="..\..\engine\Inno.Engine.Scene.Assets\Inno.Engine.Scene.Assets.csproj" />
    <ProjectReference Include="..\..\platform\Inno.Platform\Inno.Platform.csproj" />
    <ProjectReference Include="..\..\platform\Inno.Platform.ImGui\Inno.Platform.ImGui.csproj" />
  </ItemGroup>
</Project>
