<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <InnoAssemblyScope>Editor</InnoAssemblyScope>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\build\pipeline\Inno.Build\Inno.Build.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\build\pipeline\Inno.Build.Platform.MacOS\Inno.Build.Platform.MacOS.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\build\pipeline\Inno.Build.Platform.Windows\Inno.Build.Platform.Windows.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\build\toolchains\Inno.Build.Toolchains.Bgfx.Tools\Inno.Build.Toolchains.Bgfx.Tools.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Core\Inno.Editor.Core.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Exporting\Inno.Editor.Exporting.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Graph\Inno.Editor.Graph.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.ImGui\Inno.Editor.ImGui.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Inspection\Inno.Editor.Inspection.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Interactions\Inno.Editor.Interactions.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.PlayMode\Inno.Editor.PlayMode.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Rendering\Inno.Editor.Rendering.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Scripting\Inno.Editor.Scripting.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Scene\Inno.Editor.Scene.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Inno.Editor.Settings\Inno.Editor.Settings.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.FileBrowser\Inno.Editor.Panel.FileBrowser.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.GameView\Inno.Editor.Panel.GameView.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Global\Inno.Editor.Panel.Global.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Hierarchy\Inno.Editor.Panel.Hierarchy.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Inspector\Inno.Editor.Panel.Inspector.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Logging\Inno.Editor.Panel.Logging.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Stats\Inno.Editor.Panel.Stats.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.Settings\Inno.Editor.Panel.Settings.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.SceneView\Inno.Editor.Panel.SceneView.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\Panels\Inno.Editor.Panel.ShaderGraph\Inno.Editor.Panel.ShaderGraph.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\assets\Inno.Assets\Inno.Assets.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\plugins\Inno.Plugins.Authoring\Inno.Plugins.Authoring.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\core\Inno.Core.Diagnostics\Inno.Core.Diagnostics.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\core\Inno.Core.Events\Inno.Core.Events.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\core\Inno.Core.Logging\Inno.Core.Logging.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\scene\Inno.Scene\Inno.Scene.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\runtime\Inno.Runtime\Inno.Runtime.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\scene\Inno.Scene.Assets\Inno.Scene.Assets.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\platform\Inno.Platform\Inno.Platform.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\platform\Inno.Platform.Sdl3\Inno.Platform.Sdl3.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\platform\Inno.Platform.Sdl3.ImGui\Inno.Platform.Sdl3.ImGui.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering\Inno.Rendering.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering.Assets\Inno.Rendering.Assets.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering.Bgfx\Inno.Rendering.Bgfx.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering.Bgfx.ImGui\Inno.Rendering.Bgfx.ImGui.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering.Runtime\Inno.Rendering.Runtime.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Rendering.ShaderGraph\Inno.Rendering.ShaderGraph.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\assets\Inno.Assets.Pipeline\Inno.Assets.Pipeline.csproj" />
  </ItemGroup>
</Project>
