<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\core\Inno.Core.Assemblies\Inno.Core.Assemblies.csproj" />
    <ProjectReference Include="..\..\src\core\Inno.Core.Reflection\Inno.Core.Reflection.csproj" />
    <ProjectReference Include="..\Inno.Core.Assemblies.TestModule.V1\Inno.Core.Assemblies.TestModule.V1.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Inno.Core.Assemblies.TestModule.V2\Inno.Core.Assemblies.TestModule.V2.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Inno.Core.Assemblies.TestModule.Invalid\Inno.Core.Assemblies.TestModule.Invalid.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.6.6" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="CopyAssemblyTestModules" AfterTargets="Build">
    <ItemGroup>
      <TestModuleV1 Include="..\Inno.Core.Assemblies.TestModule.V1\bin\$(Configuration)\net9.0\Inno.Core.Assemblies.TestModule.dll" />
      <TestModuleV2 Include="..\Inno.Core.Assemblies.TestModule.V2\bin\$(Configuration)\net9.0\Inno.Core.Assemblies.TestModule.dll" />
      <TestModuleInvalid Include="..\Inno.Core.Assemblies.TestModule.Invalid\bin\$(Configuration)\net9.0\Inno.Core.Assemblies.TestModule.dll" />
      <TestModuleDependency Include="..\Inno.Core.Assemblies.TestDependency\bin\$(Configuration)\net9.0\Reloadable.PrivateDependency.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(TestModuleV1)" DestinationFolder="$(OutDir)Modules\V1" />
    <Copy SourceFiles="@(TestModuleV2)" DestinationFolder="$(OutDir)Modules\V2" />
    <Copy SourceFiles="@(TestModuleInvalid)" DestinationFolder="$(OutDir)Modules\Invalid" />
    <Copy SourceFiles="@(TestModuleDependency)" DestinationFolder="$(OutDir)Modules\V1" />
    <Copy SourceFiles="@(TestModuleDependency)" DestinationFolder="$(OutDir)Modules\V2" />
  </Target>
</Project>
