<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1573;CS1591</NoWarn>
    <InnoAssemblyGroup>Editor</InnoAssemblyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inno.Editor.Assets\Inno.Editor.Assets.csproj" />
    <ProjectReference Include="..\Inno.Editor.Core\Inno.Editor.Core.csproj" />
    <ProjectReference Include="..\Inno.Editor.ImGui\Inno.Editor.ImGui.csproj" />
    <ProjectReference Include="..\..\assets\Inno.Assets\Inno.Assets.csproj" />
    <ProjectReference Include="..\..\assets\Inno.Assets.Core\Inno.Assets.Core.csproj" />
    <ProjectReference Include="..\..\assets\Inno.Assets.File\Inno.Assets.File.csproj" />
    <ProjectReference Include="..\..\assets\Inno.Assets.Serialization\Inno.Assets.Serialization.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Identity\Inno.Core.Identity.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Logging\Inno.Core.Logging.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Mathematics\Inno.Core.Mathematics.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Reflection\Inno.Core.Reflection.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Serialization\Inno.Core.Serialization.csproj" />
    <ProjectReference Include="..\..\core\Inno.Core.Scripting\Inno.Core.Scripting.csproj" />
    <ProjectReference Include="..\..\engine\Inno.Engine.Scene\Inno.Engine.Scene.csproj" />
    <ProjectReference Include="..\..\engine\Inno.Engine.Scene.Assets\Inno.Engine.Scene.Assets.csproj" />
    <ProjectReference Include="..\..\platform\Inno.Platform.ImGui\Inno.Platform.ImGui.csproj" />
    <ProjectReference Include="..\..\..\native\Inno.Native.ImGui\Inno.Native.ImGui.csproj" />
  </ItemGroup>
</Project>
