using Inno.Core.Scripting;
using Inno.Rendering.Core;

[assembly: ScriptingApiNamespace(
    "InnoEngine.Rendering",
    "Inno.Rendering.Core",
    ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(GraphicsBackend), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsFeature), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsLimits), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsCapabilities), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureFormat), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureDimension), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureUsage), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureContainer), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBufferUsage), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBufferDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBufferHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBindingId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(PersistentTextureHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(PersistentBufferHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderSurfaceHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsPipelineHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ComputePipelineHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureRegion), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderVertexSemantic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderVertexFormat), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderVertexAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderVertexLayout), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderIndexFormat), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPrimitiveTopology), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderSamplerFilter), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderSamplerAddressMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderSamplerState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(PersistentBufferDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderShaderBindingKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderUniformType), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStorageAccess), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderShaderBindingDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderCullMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrontFace), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDepthCompare), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBlendFactor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBlendEquation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderBlendState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStencilCompare), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStencilOperation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStencilFaceState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStencilState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRasterState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsPipelineDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ComputePipelineDescriptor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderCommandEncoder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPassContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPassExecute<>), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPhaseId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderResourceId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderDataChannelId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPassKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderLoadAction), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderStoreAction), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderClearColor), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderViewTransform), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGraphDiagnosticSeverity), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGraphDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGraphBuilder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGraphMutationScope), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPassBuilder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RasterPassBuilder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ComputePassBuilder), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(CopyPassBuilder), ScriptingApiScope.Runtime)]
