using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Inno.Editor.Scripting;

internal static class ScriptApiStubSourceBuilder
{
    private const BindingFlags C_DECLARED_MEMBERS =
        BindingFlags.Public |
        BindingFlags.NonPublic |
        BindingFlags.Instance |
        BindingFlags.Static |
        BindingFlags.DeclaredOnly;

    [ThreadStatic]
    private static IReadOnlySet<Type>? s_exportedTypes;

    [ThreadStatic]
    private static IReadOnlyDictionary<string, string>? s_namespaceMappings;

    internal static string BuildImplementation(
        ScriptApiAssembly export,
        IReadOnlySet<Type> exportedTypes)
        => Build(
            export.exportedTypes,
            exportedTypes,
            export.assembly.GetName().Version ?? new Version(1, 0, 0, 0),
            namespaceMappings: null);

    internal static string BuildLogical(
        IReadOnlyList<Type> types,
        IReadOnlySet<Type> exportedTypes,
        IReadOnlyDictionary<string, string> namespaceMappings)
        => Build(types, exportedTypes, new Version(1, 0, 0, 0), namespaceMappings);

    private static string Build(
        IReadOnlyList<Type> types,
        IReadOnlySet<Type> exportedTypes,
        Version version,
        IReadOnlyDictionary<string, string>? namespaceMappings)
    {
        s_exportedTypes = exportedTypes;
        s_namespaceMappings = namespaceMappings;
        try
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.Append("[assembly: global::System.Reflection.AssemblyVersion(\"")
                .Append(version)
                .AppendLine("\")]");
            foreach (Type type in types.OrderBy(static value => value.FullName, StringComparer.Ordinal))
            {
                builder.Append("namespace ")
                    .Append(ResolveNamespace(type.Namespace ?? string.Empty))
                    .AppendLine()
                    .AppendLine("{");
                AppendType(builder, type);
                builder.AppendLine("}").AppendLine();
            }
            return builder.ToString();
        }
        finally
        {
            s_exportedTypes = null;
            s_namespaceMappings = null;
        }
    }

    private static void AppendType(StringBuilder builder, Type type)
    {
        if (type.IsEnum)
        {
            AppendEnum(builder, type);
            return;
        }
        if (typeof(MulticastDelegate).IsAssignableFrom(type.BaseType))
        {
            AppendDelegate(builder, type);
            return;
        }

        builder.Append("public ");
        if (type.IsClass)
        {
            if (type.IsAbstract && type.IsSealed)
                builder.Append("static ");
            else
            {
                if (type.IsAbstract)
                    builder.Append("abstract ");
                if (type.IsSealed)
                    builder.Append("sealed ");
            }
            builder.Append("class ");
        }
        else if (type.IsInterface)
        {
            builder.Append("interface ");
        }
        else
        {
            if (type.IsDefined(typeof(System.Runtime.CompilerServices.IsReadOnlyAttribute), inherit: false))
                builder.Append("readonly ");
            builder.Append("struct ");
        }
        AppendNamedType(builder, type);
        AppendBaseTypes(builder, type);
        AppendGenericConstraints(builder, type.GetGenericArguments().Where(static value => value.DeclaringMethod is null));
        builder.AppendLine().AppendLine("{");
        AppendFields(builder, type);
        AppendConstructors(builder, type);
        AppendProperties(builder, type);
        AppendEvents(builder, type);
        AppendMethods(builder, type);
        builder.AppendLine("}");
    }

    private static void AppendEnum(StringBuilder builder, Type type)
    {
        builder.Append("public enum ")
            .Append(RemoveArity(type.Name))
            .Append(" : ")
            .Append(FormatType(Enum.GetUnderlyingType(type)))
            .AppendLine()
            .AppendLine("{");
        foreach (FieldInfo field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            object value = field.GetRawConstantValue()!;
            builder.Append("    ")
                .Append(EscapeIdentifier(field.Name))
                .Append(" = ")
                .Append(FormatNumericConstant(value))
                .AppendLine(",");
        }
        builder.AppendLine("}");
    }

    private static void AppendDelegate(StringBuilder builder, Type type)
    {
        MethodInfo invoke = type.GetMethod("Invoke")
            ?? throw new InvalidOperationException($"Delegate '{type.FullName}' has no Invoke method.");
        builder.Append("public delegate ")
            .Append(FormatType(invoke.ReturnType))
            .Append(' ');
        AppendNamedType(builder, type);
        builder.Append('(');
        AppendParameters(builder, invoke.GetParameters());
        builder.Append(')');
        AppendGenericConstraints(builder, type.GetGenericArguments());
        builder.AppendLine(";");
    }

    private static void AppendNamedType(StringBuilder builder, Type type)
    {
        builder.Append(RemoveArity(type.Name));
        Type[] arguments = type.GetGenericArguments()
            .Where(static argument => argument.DeclaringMethod is null)
            .ToArray();
        if (arguments.Length == 0)
            return;
        builder.Append('<');
        for (int i = 0; i < arguments.Length; i++)
        {
            if (i > 0)
                builder.Append(", ");
            GenericParameterAttributes variance = arguments[i].GenericParameterAttributes &
                                                  GenericParameterAttributes.VarianceMask;
            if (variance == GenericParameterAttributes.Covariant)
                builder.Append("out ");
            else if (variance == GenericParameterAttributes.Contravariant)
                builder.Append("in ");
            builder.Append(arguments[i].Name);
        }
        builder.Append('>');
    }

    private static void AppendBaseTypes(StringBuilder builder, Type type)
    {
        var baseTypes = new List<Type>();
        if (type.IsClass &&
            !type.IsStaticClass() &&
            type.BaseType is not null &&
            type.BaseType != typeof(object) &&
            IsApiType(type.BaseType))
        {
            baseTypes.Add(type.BaseType);
        }
        foreach (Type interfaceType in type.GetInterfaces())
        {
            if ((interfaceType.IsPublic || interfaceType.IsNestedPublic) && IsApiType(interfaceType))
                baseTypes.Add(interfaceType);
        }
        if (baseTypes.Count == 0)
            return;
        builder.Append(" : ")
            .Append(string.Join(", ", baseTypes.Distinct().Select(FormatType)));
    }

    private static void AppendGenericConstraints(
        StringBuilder builder,
        IEnumerable<Type> genericParameters)
    {
        foreach (Type parameter in genericParameters)
        {
            GenericParameterAttributes attributes = parameter.GenericParameterAttributes;
            var constraints = new List<string>();
            if ((attributes & GenericParameterAttributes.ReferenceTypeConstraint) != 0)
                constraints.Add("class");
            bool isStruct = (attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0;
            if (isStruct)
                constraints.Add("struct");
            constraints.AddRange(parameter
                .GetGenericParameterConstraints()
                .Where(constraint => constraint != typeof(ValueType))
                .Select(FormatType));
            if (!isStruct && (attributes & GenericParameterAttributes.DefaultConstructorConstraint) != 0)
                constraints.Add("new()");
            if (constraints.Count > 0)
            {
                builder.Append(" where ")
                    .Append(parameter.Name)
                    .Append(" : ")
                    .Append(string.Join(", ", constraints));
            }
        }
    }

    private static void AppendFields(StringBuilder builder, Type type)
    {
        foreach (FieldInfo field in type.GetFields(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(field) || field.IsSpecialName || !IsApiType(field.FieldType))
                continue;
            builder.Append("    ")
                .Append(GetAccessibility(field))
                .Append(' ');
            if (field.IsLiteral)
                builder.Append("const ");
            else
            {
                if (field.IsStatic)
                    builder.Append("static ");
                if (field.IsInitOnly)
                    builder.Append("readonly ");
            }
            builder.Append(FormatType(field.FieldType))
                .Append(' ')
                .Append(EscapeIdentifier(field.Name));
            if (field.IsLiteral)
                builder.Append(" = ").Append(FormatConstant(field.GetRawConstantValue(), field.FieldType));
            builder.AppendLine(";");
        }
    }

    private static void AppendConstructors(StringBuilder builder, Type type)
    {
        if (type.IsStaticClass() || type.IsInterface)
            return;
        foreach (ConstructorInfo constructor in type.GetConstructors(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(constructor) ||
                type.IsValueType && constructor.GetParameters().Length == 0 ||
                !AreApiParameters(constructor.GetParameters()))
                continue;
            builder.Append("    ")
                .Append(GetAccessibility(constructor))
                .Append(' ')
                .Append(RemoveArity(type.Name))
                .Append('(');
            AppendParameters(builder, constructor.GetParameters());
            builder.AppendLine(") => throw new global::System.NotImplementedException();");
        }
    }

    private static void AppendProperties(StringBuilder builder, Type type)
    {
        foreach (PropertyInfo property in type.GetProperties(C_DECLARED_MEMBERS))
        {
            MethodInfo? getter = IsVisible(property.GetMethod) ? property.GetMethod : null;
            MethodInfo? setter = IsVisible(property.SetMethod) ? property.SetMethod : null;
            MethodInfo? representative = MoreVisible(getter, setter);
            if (representative is null ||
                !IsApiType(property.PropertyType) ||
                !AreApiParameters(property.GetIndexParameters()))
                continue;
            string accessibility = GetAccessibility(representative);
            builder.Append("    ")
                .Append(accessibility)
                .Append(' ');
            AppendMethodModifiers(builder, representative, type.IsInterface);
            builder.Append(FormatType(property.PropertyType)).Append(' ');
            ParameterInfo[] indexParameters = property.GetIndexParameters();
            if (indexParameters.Length > 0)
            {
                builder.Append("this[");
                AppendParameters(builder, indexParameters);
                builder.Append(']');
            }
            else
            {
                builder.Append(EscapeIdentifier(property.Name));
            }
            builder.AppendLine().AppendLine("    {");
            AppendAccessor(builder, "get", getter, accessibility);
            AppendAccessor(builder, "set", setter, accessibility);
            builder.AppendLine("    }");
        }
    }

    private static void AppendAccessor(
        StringBuilder builder,
        string keyword,
        MethodInfo? method,
        string propertyAccessibility)
    {
        if (method is null)
            return;
        builder.Append("        ");
        string accessibility = GetAccessibility(method);
        if (!string.Equals(accessibility, propertyAccessibility, StringComparison.Ordinal))
            builder.Append(accessibility).Append(' ');
        builder.Append(keyword);
        if (method.IsAbstract)
            builder.AppendLine(";");
        else
            builder.AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static void AppendEvents(StringBuilder builder, Type type)
    {
        foreach (EventInfo eventInfo in type.GetEvents(C_DECLARED_MEMBERS))
        {
            MethodInfo? accessor = MoreVisible(eventInfo.AddMethod, eventInfo.RemoveMethod);
            if (!IsVisible(accessor) || !IsApiType(eventInfo.EventHandlerType!))
                continue;
            builder.Append("    ")
                .Append(GetAccessibility(accessor!))
                .Append(' ');
            if (accessor!.IsStatic)
                builder.Append("static ");
            builder.Append("event ")
                .Append(FormatType(eventInfo.EventHandlerType!))
                .Append(' ')
                .Append(EscapeIdentifier(eventInfo.Name))
                .AppendLine(";");
        }
    }

    private static void AppendMethods(StringBuilder builder, Type type)
    {
        foreach (MethodInfo method in type.GetMethods(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(method) ||
                !IsApiMethod(method) ||
                method.Name == "Finalize" && method.GetParameters().Length == 0 ||
                method.Name.Contains('<', StringComparison.Ordinal))
                continue;
            if (method.IsSpecialName)
            {
                if (method.Name is "op_Implicit" or "op_Explicit")
                    AppendConversionOperator(builder, method);
                else if (TryGetOperator(method.Name, out string? symbol))
                    AppendOperator(builder, method, symbol!);
                continue;
            }
            builder.Append("    ")
                .Append(GetAccessibility(method))
                .Append(' ');
            AppendMethodModifiers(builder, method, type.IsInterface);
            builder.Append(FormatType(method.ReturnType))
                .Append(' ')
                .Append(EscapeIdentifier(method.Name));
            Type[] genericArguments = method.GetGenericArguments();
            if (genericArguments.Length > 0)
                builder.Append('<').Append(string.Join(", ", genericArguments.Select(static value => value.Name))).Append('>');
            builder.Append('(');
            AppendParameters(builder, method.GetParameters());
            builder.Append(')');
            AppendGenericConstraints(builder, genericArguments);
            AppendMethodBody(builder, method);
        }
    }

    private static void AppendConversionOperator(StringBuilder builder, MethodInfo method)
    {
        builder.Append("    public static ")
            .Append(method.Name == "op_Implicit" ? "implicit" : "explicit")
            .Append(" operator ")
            .Append(FormatType(method.ReturnType))
            .Append('(');
        AppendParameters(builder, method.GetParameters());
        builder.AppendLine(") => throw new global::System.NotImplementedException();");
    }

    private static void AppendOperator(StringBuilder builder, MethodInfo method, string symbol)
    {
        builder.Append("    public static ")
            .Append(FormatType(method.ReturnType))
            .Append(" operator ")
            .Append(symbol)
            .Append('(');
        AppendParameters(builder, method.GetParameters());
        builder.AppendLine(") => throw new global::System.NotImplementedException();");
    }

    private static void AppendMethodModifiers(StringBuilder builder, MethodInfo method, bool declaringTypeIsInterface)
    {
        if (method.IsStatic)
        {
            builder.Append("static ");
            return;
        }
        if (declaringTypeIsInterface)
            return;
        if (method.IsAbstract)
            builder.Append("abstract ");
        else if (method.GetBaseDefinition() != method)
        {
            if (method.IsFinal)
                builder.Append("sealed ");
            builder.Append("override ");
        }
        else if (method.IsVirtual && !method.IsFinal)
            builder.Append("virtual ");
    }

    private static void AppendMethodBody(StringBuilder builder, MethodInfo method)
    {
        if (method.IsAbstract)
            builder.AppendLine(";");
        else
            builder.AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static void AppendParameters(StringBuilder builder, IReadOnlyList<ParameterInfo> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0)
                builder.Append(", ");
            ParameterInfo parameter = parameters[i];
            if (parameter.IsDefined(typeof(ParamArrayAttribute), inherit: false))
                builder.Append("params ");
            Type parameterType = parameter.ParameterType;
            if (parameterType.IsByRef)
            {
                if (parameter.IsOut)
                    builder.Append("out ");
                else if (parameter.IsIn)
                    builder.Append("in ");
                else
                    builder.Append("ref ");
                parameterType = parameterType.GetElementType()!;
            }
            builder.Append(FormatType(parameterType))
                .Append(' ')
                .Append(EscapeIdentifier(parameter.Name ?? "value"));
            if (parameter.IsOptional)
                builder.Append(" = ").Append(FormatConstant(parameter.DefaultValue, parameterType));
        }
    }

    private static bool IsVisible(MethodBase? method)
        => method is not null &&
           (method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly);

    private static bool IsVisible(FieldInfo field)
        => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;

    private static string GetAccessibility(MethodBase method)
    {
        if (method.IsPublic)
            return "public";
        if (method.IsFamilyOrAssembly)
            return "protected internal";
        return "protected";
    }

    private static string GetAccessibility(FieldInfo field)
    {
        if (field.IsPublic)
            return "public";
        if (field.IsFamilyOrAssembly)
            return "protected internal";
        return "protected";
    }

    private static MethodInfo? MoreVisible(MethodInfo? first, MethodInfo? second)
    {
        if (!IsVisible(first))
            return IsVisible(second) ? second : null;
        if (!IsVisible(second))
            return first;
        return VisibilityRank(first!) >= VisibilityRank(second!) ? first : second;
    }

    private static int VisibilityRank(MethodBase method)
        => method.IsPublic ? 3 : method.IsFamilyOrAssembly ? 2 : method.IsFamily ? 1 : 0;

    private static string FormatType(Type type)
    {
        if (type.IsByRef || type.IsPointer)
        {
            string suffix = type.IsPointer ? "*" : string.Empty;
            return FormatType(type.GetElementType()!) + suffix;
        }
        if (type.IsArray)
            return FormatType(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
        if (type.IsGenericParameter)
            return type.Name;
        if (C_TYPE_ALIASES.TryGetValue(type, out string? alias))
            return alias;
        if (!type.IsGenericType)
            return "global::" + FormatNamedTypeName(type, removeGenericArities: false);
        Type definition = type.GetGenericTypeDefinition();
        string name = FormatNamedTypeName(definition, removeGenericArities: true);
        return "global::" + name + "<" +
               string.Join(", ", type.GetGenericArguments().Select(FormatType)) + ">";
    }

    private static string FormatNamedTypeName(Type type, bool removeGenericArities)
    {
        string implementationNamespace = type.Namespace ?? string.Empty;
        string fullName = type.FullName ?? type.Name;
        string relativeName = string.IsNullOrEmpty(implementationNamespace)
            ? fullName
            : fullName[(implementationNamespace.Length + 1)..];
        if (removeGenericArities)
            relativeName = RemoveGenericArities(relativeName);
        relativeName = relativeName.Replace('+', '.');
        string targetNamespace = ResolveNamespace(implementationNamespace);
        return string.IsNullOrEmpty(targetNamespace)
            ? relativeName
            : targetNamespace + "." + relativeName;
    }

    private static string ResolveNamespace(string implementationNamespace)
        => s_namespaceMappings is not null &&
           s_namespaceMappings.TryGetValue(implementationNamespace, out string? apiNamespace)
            ? apiNamespace
            : implementationNamespace;

    private static bool IsApiMethod(MethodInfo method)
    {
        if (!IsApiType(method.ReturnType) || !AreApiParameters(method.GetParameters()))
            return false;
        return method.GetGenericArguments()
            .SelectMany(static argument => argument.GetGenericParameterConstraints())
            .All(IsApiType);
    }

    private static bool AreApiParameters(IEnumerable<ParameterInfo> parameters)
        => parameters.All(static parameter => IsApiType(parameter.ParameterType));

    private static bool IsApiType(Type type)
    {
        if (type.IsByRef || type.IsPointer || type.IsArray)
            return IsApiType(type.GetElementType()!);
        if (type.IsGenericParameter)
            return type.GetGenericParameterConstraints().All(IsApiType);
        if (C_TYPE_ALIASES.ContainsKey(type) || type == typeof(void))
            return true;
        if (type.IsGenericType)
        {
            return IsApiNamedType(type.GetGenericTypeDefinition()) &&
                   type.GetGenericArguments().All(IsApiType);
        }
        return IsApiNamedType(type);
    }

    private static bool IsApiNamedType(Type type)
    {
        Assembly assembly = type.Assembly;
        string name = assembly.GetName().Name ?? string.Empty;
        if (assembly == typeof(object).Assembly ||
            name.StartsWith("System.", StringComparison.Ordinal) ||
            name.StartsWith("Microsoft.", StringComparison.Ordinal))
        {
            return true;
        }
        return s_exportedTypes?.Contains(type) == true;
    }

    private static string FormatConstant(object? value, Type type)
    {
        if (value is null || value == DBNull.Value || value == Missing.Value)
            return "default";
        if (type.IsEnum)
        {
            object numeric = Convert.ChangeType(
                value,
                Enum.GetUnderlyingType(type),
                CultureInfo.InvariantCulture);
            return "(" + FormatType(type) + ")" + FormatNumericConstant(numeric);
        }
        return value switch
        {
            string text => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            char character => "'" + (character == '\'' ? "\\'" : character.ToString()) + "'",
            bool boolean => boolean ? "true" : "false",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => FormatNumericConstant(value)
        };
    }

    private static string FormatNumericConstant(object value)
        => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0";

    private static bool TryGetOperator(string name, out string? symbol)
    {
        symbol = name switch
        {
            "op_Addition" => "+",
            "op_Subtraction" => "-",
            "op_Multiply" => "*",
            "op_Division" => "/",
            "op_Modulus" => "%",
            "op_Equality" => "==",
            "op_Inequality" => "!=",
            "op_LessThan" => "<",
            "op_GreaterThan" => ">",
            "op_LessThanOrEqual" => "<=",
            "op_GreaterThanOrEqual" => ">=",
            "op_UnaryNegation" => "-",
            "op_UnaryPlus" => "+",
            "op_Increment" => "++",
            "op_Decrement" => "--",
            "op_BitwiseAnd" => "&",
            "op_BitwiseOr" => "|",
            "op_ExclusiveOr" => "^",
            "op_OnesComplement" => "~",
            "op_LeftShift" => "<<",
            "op_RightShift" => ">>",
            "op_True" => "true",
            "op_False" => "false",
            _ => null
        };
        return symbol is not null;
    }

    private static string EscapeIdentifier(string value)
        => C_KEYWORDS.Contains(value) ? "@" + value : value;

    private static string RemoveArity(string value)
    {
        int separator = value.IndexOf('`');
        return separator < 0 ? value : value[..separator];
    }

    private static string RemoveGenericArities(string value)
    {
        var builder = new StringBuilder(value.Length);
        for (int i = 0; i < value.Length; i++)
        {
            if (value[i] != '`')
            {
                builder.Append(value[i]);
                continue;
            }
            while (i + 1 < value.Length && char.IsDigit(value[i + 1]))
                i++;
        }
        return builder.ToString();
    }

    private static bool IsStaticClass(this Type type) => type.IsAbstract && type.IsSealed;

    private static readonly HashSet<string> C_KEYWORDS = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    private static readonly IReadOnlyDictionary<Type, string> C_TYPE_ALIASES =
        new Dictionary<Type, string>
        {
            [typeof(void)] = "void",
            [typeof(bool)] = "bool",
            [typeof(byte)] = "byte",
            [typeof(sbyte)] = "sbyte",
            [typeof(short)] = "short",
            [typeof(ushort)] = "ushort",
            [typeof(int)] = "int",
            [typeof(uint)] = "uint",
            [typeof(long)] = "long",
            [typeof(ulong)] = "ulong",
            [typeof(char)] = "char",
            [typeof(float)] = "float",
            [typeof(double)] = "double",
            [typeof(decimal)] = "decimal",
            [typeof(string)] = "string",
            [typeof(object)] = "object"
        };
}
