<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InnoAssemblyGroup>Core</InnoAssemblyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS0108</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Inno.Platform\Inno.Platform.csproj" />
    <ProjectReference Include="..\..\..\native\Inno.Native.SDL3\Inno.Native.SDL3.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\native\Inno.Native.ImGui\Inno.Native.ImGui.csproj" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <None Include="BuiltIn\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="BuiltIn\Icons\FA-Regular-400.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="BuiltIn\Icons\FA-Solid-900.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
