<Project>
  <PropertyGroup Condition="'$(InnoAssemblyDomain)' == ''">
    <InnoAssemblyDomain>InnoInternal</InnoAssemblyDomain>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoAssemblyScope)' == ''">
    <InnoAssemblyScope>Runtime</InnoAssemblyScope>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoScriptApi)' == ''">
    <InnoScriptApi>None</InnoScriptApi>
  </PropertyGroup>
</Project>
